workflows:
  aarambh-classes-android:
    name: Aarambh Classes Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build Release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - guptaa.mohit3012@gmail.com

  aarambh-classes-ios:
    name: Aarambh Classes iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build iOS IPA (unsigned)
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - guptaa.mohit3012@gmail.com
