name: aarambh_classes
description: Mobile app for AARAMBH CLASSES (Student/Teacher/Admin) with mock data and optional Firebase integration.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3
  fl_chart: ^0.68.0
  # Uncomment when enabling Firebase
  # firebase_core: ^3.4.0
  # firebase_auth: ^5.1.4
  # cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
